# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_room',
            fields=[
                ('cls_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32)),
                ('cdata', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_room',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('stu_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('no', models.CharField(max_length=128)),
                ('stu_id', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'student_detail',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
