# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column=True, max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
