# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-02 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contacts', models.CharField(max_length=64, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('qq', models.CharField(max_length=15)),
                ('head', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
