"""
Django settings for biao project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7pid2csv%!**fn$4hc*i%u=t1@ie0@5m7%%w3x5q1s!kbu1b6u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'table',
    'teacher',
    'shopcar',
    'views01',
    'temp001',
    'upload01'
    'cache01'
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'django.middleware.cache.FetchFromCacheMiddleware'
]


ROOT_URLCONF = 'biao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ku',
        'USER':'root',
        'PASSWORD':'123456',
        'PORT':'3306',
        'HOST':'127.0.0.1',
        'CHARSET':'utf8'
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
	#将静态文件加入的项目中
    os.path.join(BASE_DIR, 'static'),
    # os.path.join(BASE_DIR, 'model03/statioc'),
)




# 上传目录
MEDIA_ROOT = BASE_DIR + '/media/'
MEDIA_URL = '/media/'

'''缓存配置'''
CACHES={
    # 'default':{
    #     # 指定缓存方式
    #     'BACKEND':'django.core.cache.backends.filebased.FileBasedCache',
    #     # 指定缓存文件的保存路径
    #     'LOCATION':'file://d:/cache',#可选
    #     '''
    #     缓存有效期
    #     正整数  默认300秒
    #     None    永不过期
    #     0       立即过期
    #     '''
    #     'TIMEOUT':500
    # }



# 必须先安装Memcacheku
# 下载python-memcache
#     'default': {
#         # 指定缓存方式(Memcache)
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#             # 指定缓存数据库的ip地址和端口
#         'LOCATION': '127.0.0.1:11211',
#         '''
#         缓存有效期
#         正整数  默认300秒
#         None    永不过期
#         0       立即过期
#         '''
#         'TIMEOUT': 500
#     }




# 使用redis缓存
    'default':{
        # 指定缓存方式
        'BACKEND':'django_redis.cache.RedisCache',
        # 指定缓存文件的保存路径
        'LOCATION':'redis://127.0.0.1:6379',
        'OPTION':{
            # 'PASSWORD':''
        },
        '''
        缓存有效期
        正整数  默认300秒
        None    永不过期
        0       立即过期
        '''
        'TIMEOUT':500
    }

}
# 全局配置
REDIS_TIMEOUT=7*24*60*60

SESSION_ENGINE='django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS='default'