# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('pay_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_pay', models.BooleanField(default=0)),
                ('pay_time', models.DateTimeField(auto_now=True)),
                ('is_ship', models.BooleanField(default=0)),
                ('ship_time', models.DateTimeField(auto_now=True)),
                ('is_receipt', models.BooleanField(default=0)),
                ('receipt_time', models.DateTimeField(auto_now=True)),
                ('ship_number', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_goods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_num', models.IntegerField()),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.BooleanField(default=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('goods_id', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='shopcar.Goods')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='shopcar.Order')),
            ],
            options={
                'db_table': 'order_goods',
            },
        ),
        migrations.CreateModel(
            name='T_goods_shopcar',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('goods_id', models.ForeignKey(db_column='g_id', on_delete=django.db.models.deletion.CASCADE, to='shopcar.Goods')),
            ],
            options={
                'db_table': 't_goods_shopcar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='t_goods_shopcar',
            name='uid',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='shopcar.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='shopcar.User'),
        ),
    ]
